Update responsive + fix noti error + Update responsive for social to have better UX when use +Add Complete CRUD and responsive for the userManagement +Fix Noti when Users dont have Permission npm run build
> portfolio@0.1.0 build
> next build

   ▲ Next.js 16.0.8 (Turbopack)
   - Environments: .env

   Creating an optimized production build ...
Turbopack build encountered 1 warnings:
[next]/internal/font/google/inter_fe8b9d92.module.css
Error while requesting resource
There was an issue requesting https://fonts.googleapis.com/css2?family=Inter:wght@100..900&display=swap

Import trace:
  Server Component:
    [next]/internal/font/google/inter_fe8b9d92.module.css
    [next]/internal/font/google/inter_fe8b9d92.js
    ./src/app/layout.tsx

> Build error occurred
Error: Turbopack build failed with 1 errors:
[next]/internal/font/google/inter_fe8b9d92.module.css
next/font: error:
Failed to fetch `Inter` from Google Fonts.

Import trace:
  Server Component:
    [next]/internal/font/google/inter_fe8b9d92.module.css
    [next]/internal/font/google/inter_fe8b9d92.js
    ./src/app/layout.tsx

    at ignore-listed frames
PS C:\Users\Garan\Desktop\NextJS\portfolio-management>

solve conflict#